---
- name: Install all
  hosts: all 
  tasks:
   - name: Install docker-py
     pip:
       name: 'https://pypi.python.org/packages/source/d/docker-py/docker-py-1.1.0.tar.gz'
       state: present
   - name: Start Docker Container
     docker_container:
       name: spring-boot-prototype-ansible
       image: "{{ dockerImagePrefix }}/{{ projectArtifactId }}:{{ projectVersion }}"
       pull: yes 
       state: started
       ports:
         - "8080:8080"
       exposed_ports:
         - 8080
