heat_template_version: 2018-08-31

description: >
  Deploy a server and attach a floating IP address
parameters:
  key_name:
    type: string
    description: Name of keypair to assign to servers
  image:
    type: string
    description: Name of image to use for servers
  name:
    type: string
    description: Name of the server
  flavor:
    type: string
    description: Flavor to use for servers
  network_id:
    type: string
    description: ID of private network
  security_group:
    type: string
    description: ID of security group
resources:
  volume_boot:
    type: OS::Cinder::Volume
    properties:
      image: CentOS-7-msgsv
      size: 20
  server:
    type: OS::Nova::Server
    properties:
      name: { get_param: name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: server_port }
      block_device_mapping:
        - device_name: vda
          volume_id: { get_resource: volume_boot }
          delete_on_termination: true

  server_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: network_id }
      security_groups: [{ get_param: security_group}]

outputs:
  server-ip:
    value: { get_attr: [server, networks, { get_param: network_id }, 0] }
    