- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - name: install docker
      apt: name=docker

      #- name: Ensure service is enabled
      #command: service docker restart***

      #- name: copying file to remote
      #copy:
      #  src: ./docker
      #  dest: /home/ubuntu/docker
    - name: Build Docker image from Dockerfile
      docker_image:
        name: web
        path: /home/ubuntu/docker
        state: build
    - name: Running the container
      docker_container:
        image: web:latest
        name: web
    - name: Check if container is running
      shell: docker ps
